version: '3'
services:
  postgresql:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
      # Where our data will be persisted
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
